version: '3.7'

services:
  node:
    image: node:latest
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - NODE_PATH=src
    volumes:
      - ./app:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "yarn install && yarn start"
    user: "1000:1000"
